trigger:
    - master

strategy:
    matrix:
        linux:
            imageName: 'ubuntu-latest'
        windows:
            imageName: 'windows-latest'

pool:
    vmImage: $(imageName)

variables:
    buildConfiguration: 'Release'

steps:

    - task: UseDotNet@2 
      displayName: ".NET Core 3.1.x"
      inputs:
        version: '3.1.x'
        packageType: sdk

    - script: sudo apt-get install -q -y iptables; sudo apt-get install -q -y ipset; sudo apt-get update;
      displayName: 'Install dependencies on Linux'
      condition: contains( variables['Agent.OS'], 'Linux' )

    - script: dotnet build --configuration $(buildConfiguration); sudo dotnet test --configuration $(buildConfiguration);
      displayName: 'Test Linux'
      condition: contains( variables['Agent.OS'], 'Linux' )

    - script: dotnet build --configuration $(buildConfiguration); dotnet test --configuration $(buildConfiguration);
      displayName: 'Test Windows'
      condition: contains( variables['Agent.OS'], 'Windows' )