trigger:
    - master

strategy:
    matrix:
        linux:
            imageName: 'ubuntu-latest'
        windows:
            imageName: 'windows-latest'

pool:
    vmImage: $(imageName)

variables:
    buildConfiguration: 'Release'

steps:
    - script: sudo apt-get install -q -y iptables; sudo apt-get install -q -y ipset; sudo apt-get update
      displayName: 'Install dependencies on Linux'
      condition: contains( variables['Agent.OS'], 'Linux' )

    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'Build All'

    - script: sudo dotnet test --configuration $(buildConfiguration)
      displayName: 'Test Linux'
      condition: contains( variables['Agent.OS'], 'Linux' )

    - script: dotnet test --configuration $(buildConfiguration)
      displayName: 'Test Windows'
      condition: contains( variables['Agent.OS'], 'Windows' )
