trigger:
    - master

strategy:
    matrix:
        linux:
            imageName: 'ubuntu-latest'
        windows:
            imageName: 'windows-latest'

pool:
    vmImage: $(imageName)

variables:
    buildConfiguration: 'Release'

steps:
    - script: sudo -i; apt-get install -q -y iptables; sudo apt-get install -q -y ipset; sudo apt-get update
      displayName: 'Install dependencies on Linux'
      condition: contains( variables['Agent.OS'], 'Linux' )

    - task: UseDotNet@2
      displayName: 'Install .Net Core SDK'
      inputs:
        packageType: 'sdk'
        version: '5.x'
        includePreviewVersions: true

    - task: NuGetToolInstaller@1

    - task: DotNetCoreCLI@2
      inputs:
        command: restore
        projects: './IPBanTests/IPBanTests.csproj'

    - task: DotNetCoreCLI@2
      inputs:
        command: build
        projects: './IPBanTests/IPBanTests.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: './IPBanTests/IPBanTests.csproj'
        arguments: '--configuration $(buildConfiguration)'
