trigger:
    - master

strategy:
    matrix:
        linux:
            imageName: 'ubuntu-latest'
        windows:
            imageName: 'windows-latest'

pool:
    vmImage: $(imageName)

variables:
    buildConfiguration: 'Release'

steps:
    - task: UseDotNet@2
      displayName: 'Install .Net Core SDK'
      inputs:
        packageType: 'sdk'
        version: '5.x'
        includePreviewVersions: true

    - task: NuGetToolInstaller@1
    - task: DotNetCoreCLI@2
      inputs:
        command: restore
        projects: './IPBanTests/IPBanTests.csproj'

    - script: sudo apt-get install -q -y iptables; sudo apt-get install -q -y ipset; sudo apt-get update
      displayName: 'Install dependencies on Linux'
      condition: contains( variables['Agent.OS'], 'Linux' )

    - script: dotnet build --configuration $(buildConfiguration) ./IPBanTests/IPBanTests.csproj
      displayName: 'Build All'

    - script: sudo dotnet test --configuration $(buildConfiguration) ./IPBanTests/IPBanTests.csproj
      displayName: 'Test Linux'
      condition: contains( variables['Agent.OS'], 'Linux' )

    - script: dotnet test --configuration $(buildConfiguration) ./IPBanTests/IPBanTests.csproj
      displayName: 'Test Windows'
      condition: contains( variables['Agent.OS'], 'Windows' )
