trigger:
    - master

strategy:
    matrix:
        linux:
            imageName: 'ubuntu-latest'
        windows:
            imageName: 'windows-latest'

pool:
    vmImage: $(imageName)

variables:
    buildConfiguration: 'Release'

steps:
    - script: sudo apt-get install iptables
      displayName: 'Install iptables on Linux'
      condition: contains( variables['Agent.OS'], 'Linux' )

    - script: sudo apt-get install ipset
      displayName: 'Install ipset on Linux'
      condition: contains( variables['Agent.OS'], 'Linux' )

    - script: sudo apt-get update
      displayName: 'Run apt-get update on Linux'
      condition: contains( variables['Agent.OS'], 'Linux' )

    - task: UseDotNet@2
      displayName: ".NET Core 3.1.x"
      inputs:
        version: '3.1.x'
        packageType: sdk

    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'Build All'
      inputs:
        version: '3.1.x'
        packageType: sdk

    - script: sudo dotnet test --configuration $(buildConfiguration)
      displayName: 'Test Linux'
      inputs:
        version: '3.1.x'
        packageType: sdk
      condition: contains( variables['Agent.OS'], 'Linux' )

    - script: dotnet test --configuration $(buildConfiguration)
      displayName: 'Test Windows'
      inputs:
        version: '3.1.x'
        packageType: sdk
      condition: contains( variables['Agent.OS'], 'Windows' )
